[workspace]
members = ["program", "client"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Daniel Cumming"]
license = "MIT"
repository = ""
description = "Solana logging program and client"